"""Telegram interface layer (layer 1 of the architecture)."""

from .bot import build_telegram_application, publish_commands, register_handlers
from .keyboards import (
    ACCEPT_SIGNAL,
    BREAK_EVEN,
    CANCEL_ORDER,
    CANCEL_PENDING,
    CLOSE_POSITION,
    CONFIRM_ENV,
    CONFIRM_TRADE,
    MODE_SWITCH,
    REJECT_SIGNAL,
    REPLACE_ORDER,
    RISK_DETAIL,
    SIGNAL_DETAILS,
    STATS_DETAIL,
    TRAILING,
    confirm_keyboard,
    env_confirm_keyboard,
    mode_button,
    mode_keyboard,
    order_keyboard,
    paper_confirm_keyboard,
    position_keyboard,
    real_confirm_keyboard,
    side_keyboard,
    signal_keyboard,
)
from .service import HELP_TEXT, CommandError, CommandResult, TelegramFacade

__all__ = [
    "ACCEPT_SIGNAL",
    "BREAK_EVEN",
    "CANCEL_ORDER",
    "CANCEL_PENDING",
    "CLOSE_POSITION",
    "CONFIRM_ENV",
    "CONFIRM_TRADE",
    "HELP_TEXT",
    "MODE_SWITCH",
    "REJECT_SIGNAL",
    "REPLACE_ORDER",
    "RISK_DETAIL",
    "SIGNAL_DETAILS",
    "STATS_DETAIL",
    "TRAILING",
    "CommandError",
    "CommandResult",
    "TelegramFacade",
    "build_telegram_application",
    "publish_commands",
    "register_handlers",
    "confirm_keyboard",
    "env_confirm_keyboard",
    "mode_button",
    "mode_keyboard",
    "order_keyboard",
    "paper_confirm_keyboard",
    "position_keyboard",
    "real_confirm_keyboard",
    "side_keyboard",
    "signal_keyboard",
]
