"""initial schema

Revision ID: 96855598aa51
Revises:
Create Date: 2026-10-01 10:21:01.890360
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '96855598aa51'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_pnl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl_pct', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('gross_profit', sa.Float(), nullable=False),
    sa.Column('gross_loss', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment', 'trade_date', name='uq_daily_env_date')
    )
    with op.batch_alter_table('daily_pnl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_pnl_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_pnl_trade_date'), ['trade_date'], unique=False)

    op.create_table('order_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('order_class', sa.String(length=16), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_audit', schema=None) as batch_op:
        batch_op.create_index('ix_order_audit_client_id', ['client_order_id'], unique=False)
        batch_op.create_index('ix_order_audit_env_created', ['environment', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_audit_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('position_protection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('trail_percent', sa.Float(), nullable=True),
    sa.Column('trail_price', sa.Float(), nullable=True),
    sa.Column('stop_order_id', sa.String(length=64), nullable=True),
    sa.Column('take_profit_order_id', sa.String(length=64), nullable=True),
    sa.Column('trailing_order_id', sa.String(length=64), nullable=True),
    sa.Column('break_even_active', sa.Boolean(), nullable=False),
    sa.Column('order_class', sa.String(length=16), nullable=True),
    sa.Column('time_stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment', 'symbol', name='uq_protection_env_symbol')
    )
    with op.batch_alter_table('position_protection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_protection_environment'), ['environment'], unique=False)

    op.create_table('settings_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_setting_scope_key')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('setup', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rr', sa.Float(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('sector', sa.String(length=48), nullable=True),
    sa.Column('tradable', sa.Boolean(), nullable=False),
    sa.Column('non_tradable_reason', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('confluences', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_env_created', ['environment', 'created_at'], unique=False)
        batch_op.create_index('ix_signals_env_symbol', ['environment', 'symbol'], unique=False)
        batch_op.create_index('ix_signals_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_quality'), ['quality'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_trade_id'), ['trade_id'], unique=False)

    op.create_table('trade_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_events_environment'), ['environment'], unique=False)
        batch_op.create_index('ix_trade_events_trade', ['trade_id', 'created_at'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('setup', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('sector', sa.String(length=48), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rr', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=False),
    sa.Column('mfe', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('mfe_r', sa.Float(), nullable=False),
    sa.Column('mae_r', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('confluences', sa.JSON(), nullable=False),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason_note', sa.Text(), nullable=True),
    sa.Column('entry_order_id', sa.String(length=64), nullable=True),
    sa.Column('exit_order_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('stop_order_id', sa.String(length=64), nullable=True),
    sa.Column('take_profit_order_id', sa.String(length=64), nullable=True),
    sa.Column('trailing_order_id', sa.String(length=64), nullable=True),
    sa.Column('has_stop', sa.Boolean(), nullable=False),
    sa.Column('time_stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_client_order_id'), ['client_order_id'], unique=False)
        batch_op.create_index('ix_trades_env_closed', ['environment', 'closed_at'], unique=False)
        batch_op.create_index('ix_trades_env_opened', ['environment', 'opened_at'], unique=False)
        batch_op.create_index('ix_trades_env_status', ['environment', 'status'], unique=False)
        batch_op.create_index('ix_trades_env_strategy', ['environment', 'strategy'], unique=False)
        batch_op.create_index('ix_trades_env_symbol', ['environment', 'symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_exit_reason'), ['exit_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_sector'))
        batch_op.drop_index(batch_op.f('ix_trades_exit_reason'))
        batch_op.drop_index(batch_op.f('ix_trades_environment'))
        batch_op.drop_index('ix_trades_env_symbol')
        batch_op.drop_index('ix_trades_env_strategy')
        batch_op.drop_index('ix_trades_env_status')
        batch_op.drop_index('ix_trades_env_opened')
        batch_op.drop_index('ix_trades_env_closed')
        batch_op.drop_index(batch_op.f('ix_trades_client_order_id'))

    op.drop_table('trades')
    with op.batch_alter_table('trade_events', schema=None) as batch_op:
        batch_op.drop_index('ix_trade_events_trade')
        batch_op.drop_index(batch_op.f('ix_trade_events_environment'))

    op.drop_table('trade_events')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_trade_id'))
        batch_op.drop_index(batch_op.f('ix_signals_quality'))
        batch_op.drop_index('ix_signals_fingerprint')
        batch_op.drop_index('ix_signals_env_symbol')
        batch_op.drop_index('ix_signals_env_created')

    op.drop_table('signals')
    op.drop_table('settings_override')
    with op.batch_alter_table('position_protection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_protection_environment'))

    op.drop_table('position_protection')
    with op.batch_alter_table('order_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_audit_idempotency_key'))
        batch_op.drop_index('ix_order_audit_env_created')
        batch_op.drop_index('ix_order_audit_client_id')

    op.drop_table('order_audit')
    with op.batch_alter_table('daily_pnl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_pnl_trade_date'))
        batch_op.drop_index(batch_op.f('ix_daily_pnl_environment'))

    op.drop_table('daily_pnl')
    op.drop_table('app_state')
    # ### end Alembic commands ###
