"""signals htf_timeframe and nullable order_audit symbol/side

Revision ID: f4e0ba9f112b
Revises: 6cf6a5e9c120
Create Date: 2026-10-01 12:28:41.259665
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f4e0ba9f112b'
down_revision: str | None = '6cf6a5e9c120'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_audit', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('side',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('htf_timeframe', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('htf_timeframe')

    with op.batch_alter_table('order_audit', schema=None) as batch_op:
        batch_op.alter_column('side',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
